name: Claide
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: com.hexul
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.1"

targets:
  Claide:
    type: application
    platform: macOS
    sources:
      - Claide
    dependencies:
      - package: Sparkle
    info:
      path: Claide/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSUIElement: false
        SUFeedURL: "https://raw.githubusercontent.com/hex/Claide/main/appcast.xml"
        SUPublicEDKey: "VJR0Igvi956+S07119jBXK+/rt1QjpUB//YJYx7ZAHs="
    preBuildScripts:
      - name: Build Rust Library
        script: '"${PROJECT_DIR}/rust/build-universal.sh"'
        basedOnDependencyAnalysis: false
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Claide/Claide.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.hexul.claide
        DEVELOPMENT_TEAM: 7G4UQW35EL
        MARKETING_VERSION: "2026.2.2"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LIBRARY_SEARCH_PATHS: "$(PROJECT_DIR)/rust/target/lib"
        SWIFT_OBJC_BRIDGING_HEADER: Claide/BridgingHeader.h
        OTHER_LDFLAGS: "-lclaide_terminal"
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: Claide/Claide.entitlements
      properties:
        com.apple.security.app-sandbox: false

  ClaideTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ClaideTests
    dependencies:
      - target: Claide
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
