name: Claide
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: com.hexul
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  SwiftTerm:
    url: https://github.com/hex/SwiftTerm
    revision: da9d4feffc06cd153c859f825f691767ba51d276

targets:
  Claide:
    type: application
    platform: macOS
    sources:
      - Claide
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Claide/Claide.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.hexul.claide
        DEVELOPMENT_TEAM: 7G4UQW35EL
        MARKETING_VERSION: "2026.2.1"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: SwiftTerm
    entitlements:
      path: Claide/Claide.entitlements
      properties:
        com.apple.security.app-sandbox: false

  ClaideTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ClaideTests
    dependencies:
      - target: Claide
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
